### ISSUE TITLE
 ERROR [internal] load metadata for docker.io/library/python:3.11-slim   

### ISSUE THREAD

**Issue by chenggangqcg** [topoteretes/cognee#117]
cognee %sudo docker compose up cognee
Password:
[+] Building 1.1s (2/3)
[+] Building 1.1s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 32B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 34B                                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/library/python:3.11-slim                                                    1.0s
------
 > [internal] load metadata for docker.io/library/python:3.11-slim:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``

**Comment by Vasilije1990** [comment]
Did you define credentials in .env file?

**Comment by chenggangqcg** [comment]
After I manually pulled the python:3.11-slim image， it worked.
