### ISSUE TITLE
[COG-620] Bug: code_graph_pipeline can't process false "Class"

### ISSUE THREAD

**Issue by alekszievr** [topoteretes/cognee#217]
code_graph_pipeline runs into a Pydantic error if the input text contains the word "Class" without it being an actual Class definition (e.g. in documentation)

Reproduce:

```python
import cognee

await cognee.prune.prune_data()
await cognee.prune.prune_system(metadata = True)

dataset_name = "test"
await cognee.add(["This is just plain text with the word Class in it."])
await code_graph_pipeline([dataset_name])
```

The error message is:

pydantic.errors.PydanticUserError: `Class` is not fully defined; you should define `Function`, then call `Class.model_rebuild()`.

<sub>From [SyncLinear.com](https://synclinear.com) | [COG-620](https://linear.app/cognee/issue/COG-620/bug-code-graph-pipeline-cant-process-false-class-copy)</sub>

**Comment by hajdul88** [comment]
I checked this, first I think the "reproduce example" needs the name of the dataset also in the add parameter as in this way will use the default "main_dataset" name, and the second Task will not be able to find it. Here is the fixed version:

`
dataset_name = "test"
    await cognee.add(["This is just plain text with the word Class in it."], dataset_name=dataset_name)
    await code_graph_pipeline([dataset_name])
`


I tried also to reproduce it and I think it works just fine, for me the type in the code is this:

![Screenshot 2024-11-15 at 10 53 21](https://github.com/user-attachments/assets/16a240bc-fdc8-4e0c-9f78-c8febb1982fe)


also it created a graph in neo4j:

![Screenshot 2024-11-15 at 10 54 26](https://github.com/user-attachments/assets/2af831d1-433f-4405-beb3-2ab600861806)

**Comment by alekszievr** [comment]
Actually, I can't reproduce the bug even with the original example code. Let's close this, thanks for checking it!

**Comment by alekszievr** [comment]
Sorry, my original example was not correct. I can reproduce the error using this line:
await cognee.add(["This is just plain text with the word Class dfgjafgdsa."], dataset_name)

**Comment by hajdul88** [comment]
Fixed in https://github.com/topoteretes/cognee/pull/229
