### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by prrao87** [topoteretes/cognee#55]
Is there any reason that Python 3.11 isn't yet supported? I was trying to get a simple cognee example up and running but it's surprising to me that it only supports up to Python 3.10.

**Comment by Vasilije1990** [comment]
Unstructured library which we use asked for python 3.10
I will check if we can remove it as a dependency

**Comment by Vasilije1990** [comment]
We fixed it. Should be Python 3.11 now
