### ISSUE TITLE
[COG-171] Add Apache AGE as a graph solution

### ISSUE THREAD

**Issue by Vasilije1990** [topoteretes/cognee#80]
<sub>From [SyncLinear.com](https://synclinear.com) | [COG-171](https://linear.app/cognee/issue/COG-171/add-apache-age-as-a-graph-solution)</sub>

**Comment by darinkishore** [comment]
hey! qq—would yall be interesting in adding edgeDB support? Any ideas for how much work that would be? I can try and take a crack at it, have been super excited about it recently (syntax feels more intuitive than neo4j, built on postgres, (ie: pgvector support + fixed enforcable schema), and 5.0 added native RAG support as well.
