### ISSUE TITLE
Catalog Error: Table with name file_metadata does not exist! 

### ISSUE THREAD

**Issue by andysingal** [topoteretes/cognee#93]
<img width="1363" alt="Screenshot 2024-05-06 at 6 26 02 PM" src="https://github.com/topoteretes/cognee/assets/20493493/5c17dbab-2546-4854-aec8-e737a13be1e5">

<img width="1324" alt="Screenshot 2024-05-06 at 6 25 39 PM" src="https://github.com/topoteretes/cognee/assets/20493493/3666c552-6b27-4abd-afac-f82bf52aa1ab">

Also had challenges with forming the graph: https://motherduck.com/blog/streamlining-ai-agents-duckdb-rag-solutions/

**Comment by Vasilije1990** [comment]
Hey, seems you don't have the dataset needed to load this example notebook on your local.

What was the issue with the graph generation?
